//------------------------------------------------------------------------------
// <auto-generated>
//     Ten kod został wygenerowany przez narzędzie.
//     Wersja wykonawcza:4.0.30319.42000
//
//     Zmiany w tym pliku mogą spowodować nieprawidłowe zachowanie i zostaną utracone, jeśli
//     kod zostanie ponownie wygenerowany.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVVMMoj.Uslugi {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Uzytkownik", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Uzytkownik : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LoginField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ImieField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NazwiskoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string JednostkaField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Login {
            get {
                return this.LoginField;
            }
            set {
                if ((object.ReferenceEquals(this.LoginField, value) != true)) {
                    this.LoginField = value;
                    this.RaisePropertyChanged("Login");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Imie {
            get {
                return this.ImieField;
            }
            set {
                if ((object.ReferenceEquals(this.ImieField, value) != true)) {
                    this.ImieField = value;
                    this.RaisePropertyChanged("Imie");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Nazwisko {
            get {
                return this.NazwiskoField;
            }
            set {
                if ((object.ReferenceEquals(this.NazwiskoField, value) != true)) {
                    this.NazwiskoField = value;
                    this.RaisePropertyChanged("Nazwisko");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string Jednostka {
            get {
                return this.JednostkaField;
            }
            set {
                if ((object.ReferenceEquals(this.JednostkaField, value) != true)) {
                    this.JednostkaField = value;
                    this.RaisePropertyChanged("Jednostka");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Zdarzenia", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Zdarzenia : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nazwaField;
        
        private System.Nullable<System.DateTime> dataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string opisField;
        
        private System.Nullable<int> sprzedażField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int id {
            get {
                return this.idField;
            }
            set {
                if ((this.idField.Equals(value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string nazwa {
            get {
                return this.nazwaField;
            }
            set {
                if ((object.ReferenceEquals(this.nazwaField, value) != true)) {
                    this.nazwaField = value;
                    this.RaisePropertyChanged("nazwa");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public System.Nullable<System.DateTime> data {
            get {
                return this.dataField;
            }
            set {
                if ((this.dataField.Equals(value) != true)) {
                    this.dataField = value;
                    this.RaisePropertyChanged("data");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string opis {
            get {
                return this.opisField;
            }
            set {
                if ((object.ReferenceEquals(this.opisField, value) != true)) {
                    this.opisField = value;
                    this.RaisePropertyChanged("opis");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public System.Nullable<int> sprzedaż {
            get {
                return this.sprzedażField;
            }
            set {
                if ((this.sprzedażField.Equals(value) != true)) {
                    this.sprzedażField = value;
                    this.RaisePropertyChanged("sprzedaż");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Uslugi.WebServiceSoap")]
    public interface WebServiceSoap {
        
        // CODEGEN: Trwa generowanie kontraktu komunikatu, ponieważ nazwa elementu aAa z przestrzeni nazw http://tempuri.org/ nie ma atrybutu nillable.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        MVVMMoj.Uslugi.HelloWorldResponse HelloWorld(MVVMMoj.Uslugi.HelloWorldRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        System.Threading.Tasks.Task<MVVMMoj.Uslugi.HelloWorldResponse> HelloWorldAsync(MVVMMoj.Uslugi.HelloWorldRequest request);
        
        // CODEGEN: Trwa generowanie kontraktu komunikatu, ponieważ nazwa elementu OdczytZBazyResult z przestrzeni nazw http://tempuri.org/ nie ma atrybutu nillable.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/OdczytZBazy", ReplyAction="*")]
        MVVMMoj.Uslugi.OdczytZBazyResponse OdczytZBazy(MVVMMoj.Uslugi.OdczytZBazyRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/OdczytZBazy", ReplyAction="*")]
        System.Threading.Tasks.Task<MVVMMoj.Uslugi.OdczytZBazyResponse> OdczytZBazyAsync(MVVMMoj.Uslugi.OdczytZBazyRequest request);
        
        // CODEGEN: Trwa generowanie kontraktu komunikatu, ponieważ nazwa elementu OdczytZBazyWartosciZdarzenResult z przestrzeni nazw http://tempuri.org/ nie ma atrybutu nillable.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/OdczytZBazyWartosciZdarzen", ReplyAction="*")]
        MVVMMoj.Uslugi.OdczytZBazyWartosciZdarzenResponse OdczytZBazyWartosciZdarzen(MVVMMoj.Uslugi.OdczytZBazyWartosciZdarzenRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/OdczytZBazyWartosciZdarzen", ReplyAction="*")]
        System.Threading.Tasks.Task<MVVMMoj.Uslugi.OdczytZBazyWartosciZdarzenResponse> OdczytZBazyWartosciZdarzenAsync(MVVMMoj.Uslugi.OdczytZBazyWartosciZdarzenRequest request);
        
        // CODEGEN: Trwa generowanie kontraktu komunikatu, ponieważ nazwa elementu listaZeZmienionymiZdarzeniami z przestrzeni nazw http://tempuri.org/ nie ma atrybutu nillable.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ZapisDoBazy", ReplyAction="*")]
        MVVMMoj.Uslugi.ZapisDoBazyResponse ZapisDoBazy(MVVMMoj.Uslugi.ZapisDoBazyRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ZapisDoBazy", ReplyAction="*")]
        System.Threading.Tasks.Task<MVVMMoj.Uslugi.ZapisDoBazyResponse> ZapisDoBazyAsync(MVVMMoj.Uslugi.ZapisDoBazyRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorld", Namespace="http://tempuri.org/", Order=0)]
        public MVVMMoj.Uslugi.HelloWorldRequestBody Body;
        
        public HelloWorldRequest() {
        }
        
        public HelloWorldRequest(MVVMMoj.Uslugi.HelloWorldRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class HelloWorldRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string aAa;
        
        public HelloWorldRequestBody() {
        }
        
        public HelloWorldRequestBody(string aAa) {
            this.aAa = aAa;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorldResponse", Namespace="http://tempuri.org/", Order=0)]
        public MVVMMoj.Uslugi.HelloWorldResponseBody Body;
        
        public HelloWorldResponse() {
        }
        
        public HelloWorldResponse(MVVMMoj.Uslugi.HelloWorldResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class HelloWorldResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HelloWorldResult;
        
        public HelloWorldResponseBody() {
        }
        
        public HelloWorldResponseBody(string HelloWorldResult) {
            this.HelloWorldResult = HelloWorldResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class OdczytZBazyRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="OdczytZBazy", Namespace="http://tempuri.org/", Order=0)]
        public MVVMMoj.Uslugi.OdczytZBazyRequestBody Body;
        
        public OdczytZBazyRequest() {
        }
        
        public OdczytZBazyRequest(MVVMMoj.Uslugi.OdczytZBazyRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class OdczytZBazyRequestBody {
        
        public OdczytZBazyRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class OdczytZBazyResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="OdczytZBazyResponse", Namespace="http://tempuri.org/", Order=0)]
        public MVVMMoj.Uslugi.OdczytZBazyResponseBody Body;
        
        public OdczytZBazyResponse() {
        }
        
        public OdczytZBazyResponse(MVVMMoj.Uslugi.OdczytZBazyResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class OdczytZBazyResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public MVVMMoj.Uslugi.Uzytkownik[] OdczytZBazyResult;
        
        public OdczytZBazyResponseBody() {
        }
        
        public OdczytZBazyResponseBody(MVVMMoj.Uslugi.Uzytkownik[] OdczytZBazyResult) {
            this.OdczytZBazyResult = OdczytZBazyResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class OdczytZBazyWartosciZdarzenRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="OdczytZBazyWartosciZdarzen", Namespace="http://tempuri.org/", Order=0)]
        public MVVMMoj.Uslugi.OdczytZBazyWartosciZdarzenRequestBody Body;
        
        public OdczytZBazyWartosciZdarzenRequest() {
        }
        
        public OdczytZBazyWartosciZdarzenRequest(MVVMMoj.Uslugi.OdczytZBazyWartosciZdarzenRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class OdczytZBazyWartosciZdarzenRequestBody {
        
        public OdczytZBazyWartosciZdarzenRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class OdczytZBazyWartosciZdarzenResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="OdczytZBazyWartosciZdarzenResponse", Namespace="http://tempuri.org/", Order=0)]
        public MVVMMoj.Uslugi.OdczytZBazyWartosciZdarzenResponseBody Body;
        
        public OdczytZBazyWartosciZdarzenResponse() {
        }
        
        public OdczytZBazyWartosciZdarzenResponse(MVVMMoj.Uslugi.OdczytZBazyWartosciZdarzenResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class OdczytZBazyWartosciZdarzenResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public MVVMMoj.Uslugi.Zdarzenia[] OdczytZBazyWartosciZdarzenResult;
        
        public OdczytZBazyWartosciZdarzenResponseBody() {
        }
        
        public OdczytZBazyWartosciZdarzenResponseBody(MVVMMoj.Uslugi.Zdarzenia[] OdczytZBazyWartosciZdarzenResult) {
            this.OdczytZBazyWartosciZdarzenResult = OdczytZBazyWartosciZdarzenResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ZapisDoBazyRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ZapisDoBazy", Namespace="http://tempuri.org/", Order=0)]
        public MVVMMoj.Uslugi.ZapisDoBazyRequestBody Body;
        
        public ZapisDoBazyRequest() {
        }
        
        public ZapisDoBazyRequest(MVVMMoj.Uslugi.ZapisDoBazyRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ZapisDoBazyRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public MVVMMoj.Uslugi.Zdarzenia[] listaZeZmienionymiZdarzeniami;
        
        public ZapisDoBazyRequestBody() {
        }
        
        public ZapisDoBazyRequestBody(MVVMMoj.Uslugi.Zdarzenia[] listaZeZmienionymiZdarzeniami) {
            this.listaZeZmienionymiZdarzeniami = listaZeZmienionymiZdarzeniami;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ZapisDoBazyResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ZapisDoBazyResponse", Namespace="http://tempuri.org/", Order=0)]
        public MVVMMoj.Uslugi.ZapisDoBazyResponseBody Body;
        
        public ZapisDoBazyResponse() {
        }
        
        public ZapisDoBazyResponse(MVVMMoj.Uslugi.ZapisDoBazyResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ZapisDoBazyResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ZapisDoBazyResult;
        
        public ZapisDoBazyResponseBody() {
        }
        
        public ZapisDoBazyResponseBody(string ZapisDoBazyResult) {
            this.ZapisDoBazyResult = ZapisDoBazyResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebServiceSoapChannel : MVVMMoj.Uslugi.WebServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebServiceSoapClient : System.ServiceModel.ClientBase<MVVMMoj.Uslugi.WebServiceSoap>, MVVMMoj.Uslugi.WebServiceSoap {
        
        public WebServiceSoapClient() {
        }
        
        public WebServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MVVMMoj.Uslugi.HelloWorldResponse MVVMMoj.Uslugi.WebServiceSoap.HelloWorld(MVVMMoj.Uslugi.HelloWorldRequest request) {
            return base.Channel.HelloWorld(request);
        }
        
        public string HelloWorld(string aAa) {
            MVVMMoj.Uslugi.HelloWorldRequest inValue = new MVVMMoj.Uslugi.HelloWorldRequest();
            inValue.Body = new MVVMMoj.Uslugi.HelloWorldRequestBody();
            inValue.Body.aAa = aAa;
            MVVMMoj.Uslugi.HelloWorldResponse retVal = ((MVVMMoj.Uslugi.WebServiceSoap)(this)).HelloWorld(inValue);
            return retVal.Body.HelloWorldResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MVVMMoj.Uslugi.HelloWorldResponse> MVVMMoj.Uslugi.WebServiceSoap.HelloWorldAsync(MVVMMoj.Uslugi.HelloWorldRequest request) {
            return base.Channel.HelloWorldAsync(request);
        }
        
        public System.Threading.Tasks.Task<MVVMMoj.Uslugi.HelloWorldResponse> HelloWorldAsync(string aAa) {
            MVVMMoj.Uslugi.HelloWorldRequest inValue = new MVVMMoj.Uslugi.HelloWorldRequest();
            inValue.Body = new MVVMMoj.Uslugi.HelloWorldRequestBody();
            inValue.Body.aAa = aAa;
            return ((MVVMMoj.Uslugi.WebServiceSoap)(this)).HelloWorldAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MVVMMoj.Uslugi.OdczytZBazyResponse MVVMMoj.Uslugi.WebServiceSoap.OdczytZBazy(MVVMMoj.Uslugi.OdczytZBazyRequest request) {
            return base.Channel.OdczytZBazy(request);
        }
        
        public MVVMMoj.Uslugi.Uzytkownik[] OdczytZBazy() {
            MVVMMoj.Uslugi.OdczytZBazyRequest inValue = new MVVMMoj.Uslugi.OdczytZBazyRequest();
            inValue.Body = new MVVMMoj.Uslugi.OdczytZBazyRequestBody();
            MVVMMoj.Uslugi.OdczytZBazyResponse retVal = ((MVVMMoj.Uslugi.WebServiceSoap)(this)).OdczytZBazy(inValue);
            return retVal.Body.OdczytZBazyResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MVVMMoj.Uslugi.OdczytZBazyResponse> MVVMMoj.Uslugi.WebServiceSoap.OdczytZBazyAsync(MVVMMoj.Uslugi.OdczytZBazyRequest request) {
            return base.Channel.OdczytZBazyAsync(request);
        }
        
        public System.Threading.Tasks.Task<MVVMMoj.Uslugi.OdczytZBazyResponse> OdczytZBazyAsync() {
            MVVMMoj.Uslugi.OdczytZBazyRequest inValue = new MVVMMoj.Uslugi.OdczytZBazyRequest();
            inValue.Body = new MVVMMoj.Uslugi.OdczytZBazyRequestBody();
            return ((MVVMMoj.Uslugi.WebServiceSoap)(this)).OdczytZBazyAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MVVMMoj.Uslugi.OdczytZBazyWartosciZdarzenResponse MVVMMoj.Uslugi.WebServiceSoap.OdczytZBazyWartosciZdarzen(MVVMMoj.Uslugi.OdczytZBazyWartosciZdarzenRequest request) {
            return base.Channel.OdczytZBazyWartosciZdarzen(request);
        }
        
        public MVVMMoj.Uslugi.Zdarzenia[] OdczytZBazyWartosciZdarzen() {
            MVVMMoj.Uslugi.OdczytZBazyWartosciZdarzenRequest inValue = new MVVMMoj.Uslugi.OdczytZBazyWartosciZdarzenRequest();
            inValue.Body = new MVVMMoj.Uslugi.OdczytZBazyWartosciZdarzenRequestBody();
            MVVMMoj.Uslugi.OdczytZBazyWartosciZdarzenResponse retVal = ((MVVMMoj.Uslugi.WebServiceSoap)(this)).OdczytZBazyWartosciZdarzen(inValue);
            return retVal.Body.OdczytZBazyWartosciZdarzenResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MVVMMoj.Uslugi.OdczytZBazyWartosciZdarzenResponse> MVVMMoj.Uslugi.WebServiceSoap.OdczytZBazyWartosciZdarzenAsync(MVVMMoj.Uslugi.OdczytZBazyWartosciZdarzenRequest request) {
            return base.Channel.OdczytZBazyWartosciZdarzenAsync(request);
        }
        
        public System.Threading.Tasks.Task<MVVMMoj.Uslugi.OdczytZBazyWartosciZdarzenResponse> OdczytZBazyWartosciZdarzenAsync() {
            MVVMMoj.Uslugi.OdczytZBazyWartosciZdarzenRequest inValue = new MVVMMoj.Uslugi.OdczytZBazyWartosciZdarzenRequest();
            inValue.Body = new MVVMMoj.Uslugi.OdczytZBazyWartosciZdarzenRequestBody();
            return ((MVVMMoj.Uslugi.WebServiceSoap)(this)).OdczytZBazyWartosciZdarzenAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MVVMMoj.Uslugi.ZapisDoBazyResponse MVVMMoj.Uslugi.WebServiceSoap.ZapisDoBazy(MVVMMoj.Uslugi.ZapisDoBazyRequest request) {
            return base.Channel.ZapisDoBazy(request);
        }
        
        public string ZapisDoBazy(MVVMMoj.Uslugi.Zdarzenia[] listaZeZmienionymiZdarzeniami) {
            MVVMMoj.Uslugi.ZapisDoBazyRequest inValue = new MVVMMoj.Uslugi.ZapisDoBazyRequest();
            inValue.Body = new MVVMMoj.Uslugi.ZapisDoBazyRequestBody();
            inValue.Body.listaZeZmienionymiZdarzeniami = listaZeZmienionymiZdarzeniami;
            MVVMMoj.Uslugi.ZapisDoBazyResponse retVal = ((MVVMMoj.Uslugi.WebServiceSoap)(this)).ZapisDoBazy(inValue);
            return retVal.Body.ZapisDoBazyResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MVVMMoj.Uslugi.ZapisDoBazyResponse> MVVMMoj.Uslugi.WebServiceSoap.ZapisDoBazyAsync(MVVMMoj.Uslugi.ZapisDoBazyRequest request) {
            return base.Channel.ZapisDoBazyAsync(request);
        }
        
        public System.Threading.Tasks.Task<MVVMMoj.Uslugi.ZapisDoBazyResponse> ZapisDoBazyAsync(MVVMMoj.Uslugi.Zdarzenia[] listaZeZmienionymiZdarzeniami) {
            MVVMMoj.Uslugi.ZapisDoBazyRequest inValue = new MVVMMoj.Uslugi.ZapisDoBazyRequest();
            inValue.Body = new MVVMMoj.Uslugi.ZapisDoBazyRequestBody();
            inValue.Body.listaZeZmienionymiZdarzeniami = listaZeZmienionymiZdarzeniami;
            return ((MVVMMoj.Uslugi.WebServiceSoap)(this)).ZapisDoBazyAsync(inValue);
        }
    }
}
